app = "kompli-bot"

[build]
  image = "python:3.11-slim"

[env]
  # BOT_TOKEN и PUBLIC_URL не храним здесь, используем fly secrets

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

[processes.web]
  command = "uvicorn main:app --host 0.0.0.0 --port 8080"
